### ISSUE TITLE
[style] Change in New Content button UI and replace it with "+" button only.

### ISSUE THREAD

**Issue by Anmol-Agrawal-Codes** [Taaveez/Taaveez-android#107]
### What's the style idea?

Change in New Content button UI and replace it with "+" button only.

Before:
![Screenshot 2023-08-21 173336](https://github.com/Taaveez/Taaveez-android/assets/100439294/4e6994f2-c419-49cf-a57a-474ccbeeddf5)

After:
![image](https://github.com/Taaveez/Taaveez-android/assets/100439294/d45a21c6-fb06-47aa-b49f-d464b2b7acca)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Not required
