### ISSUE TITLE
A simple login and signup page

### ISSUE THREAD

**Issue by praveer7398** [Taaveez/Taaveez-android#111]
### Is your feature request related to a problem? Please describe.

A login and signup page will be used to track down number of users using this app and we can add a comment section in each poem so that others can appreciate the artist.

Plz add IWOC24 badge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
This app currently serves offline users. Optionally, you can include an offline backup feature. Integration of online functionality is planned for a later phase.
