### ISSUE TITLE
Want to improve the design of bottom navigation bar

### ISSUE THREAD

**Issue by vishal8113** [Taaveez/Taaveez-android#29]
### Is your feature request related to a problem? Please describe.

I want to improve the design of the bottom navigation bar. So, that it looks more attractive and Impressive

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sajal-web** [comment]
hi can you assign me this ? ,
i will provide some better look in the xml...

**Comment by supriyakashyap1** [comment]
hi, i want to contribute in this too. can you assign me this?

**Comment by Suryansh1720001** [comment]
Hello,
Could you please provide me with a sample template so that I can better understand your request and assign accordingly?

**Comment by AryanShivva** [comment]
hi can you assign me this , i want to improve  the design of the bottom navigation bar....

**Comment by VashuChoudhary1** [comment]
hello assign this work to me.

**Comment by Suryansh1720001** [comment]
If anyone wants to enhance the entire app's user interface, it would be more beneficial than focusing on specific components. In that case, please refer to other issues related to UI improvements or create a new one if necessary.
