### ISSUE TITLE
Making it user friendly

### ISSUE THREAD

**Issue by ayush290104** [Taaveez/Taaveez-android#37]
### Is your feature request related to a problem? Please describe.

If someone installs the app for first time there is no such guide so they can understand the actual purpose of the app. I want to contribute in such a way that we can differentiate it from other notes app.

### Describe the solution you'd like

We can add a tuttorial at the starting when a user opens for the first time.
We can give some features to store their art on basis of sorting and filtering.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hello @ayush290104 
Can you show me some sample-tamplet for that first?

**Comment by Suryansh1720001** [comment]
@ayush290104 
Please give me an update on this. If you are referring to the issue related to the intro screen, you may find similar open issues that address the same concern.

**Comment by Suryansh1720001** [comment]
Since there has been no response from @ayush290104, I am proceeding to close this issue now.
