### ISSUE TITLE
Project Structuring 

### ISSUE THREAD

**Issue by javaman97** [Taaveez/Taaveez-android#40]
### What is Package Structuring or Organization?
"The process of creating packages in Android is commonly referred to as "package structuring" or "package organization."
It involves organizing your Java or Kotlin classes into logical groups by creating separate packages."

### Benefits
1)This helps maintain a well-structured and modular codebase, making navigating and managing your application's components easier.
2 ) By dividing your code into packages, You can achieve better code organization, encapsulation, and reusability

### Describe the solution you'd like

![project](https://github.com/Suryansh1720001/Taaveez/assets/75328768/ea9d2369-86f2-4ec0-8783-ebce64d14e8e)

I will create different packages for various activities, fragments, databases, and other components that would help the project to be structured and organized better.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by javaman97** [comment]
Assign me this issue,I would be happy to contribute !

**Comment by Suryansh1720001** [comment]
Many contributors have already raised this issue, so please check other related issues before creating a duplicate.

**Comment by javaman97** [comment]
Sure, I will try to contribute by raising some more issues that are unique.
