### ISSUE TITLE
Addition in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [Taaveez/Taaveez-android#54]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, config.yml for all other issues etc*

Please assign this issue to me under Gssoc'23 @Suryansh1720001 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Suryansh1720001** [comment]
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this.
