### ISSUE TITLE
Feature Request: Designing a website for Taaveez

### ISSUE THREAD

**Issue by yaten2302** [Taaveez/Taaveez-android#60]
### Is your feature request related to a problem? Please describe.

Hi @Suryansh1720001, I was having an idea of designing a website for "Taaveez" would be a great idea?

The app is very useful for saving poetries, stories etc... I think that if there is a website for this, then it will attract more and more users.

### Describe the solution you'd like

Here all the details of this app will be added with some demo screenshots, videos, features and some description about the app.
Also there can be a "Contact page" and "FAQs section". This will be easier for the user to get to know about the project very easily.

Also it will attract more users because of the beautiful UI of the website and the app.

Please assign this task to me under GSSOC'23, as I want to work on this issue 🙏
I will start making the prototype and the website once you approve.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hey @yaten2302 
Creating a website dedicated to Taaveez and its related content is a great idea. The website would provide users with various features, such as a download link for the associated app on the Play Store, a comprehensive FAQ section, a contact page for inquiries, an informative About section, and additional relevant information.
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this app and its theme.
