### ISSUE TITLE
UI Improvements and Clean Architecture Implementation

### ISSUE THREAD

**Issue by abhinavkr2108** [Taaveez/Taaveez-android#63]
### Is your feature request related to a problem? Please describe.

This App lacks certain things like: 

- Navigation Component
- Clean Architecture
- Sign In/ Sign Up User
- dependency Injection

### Describe the solution you'd like

Solutions that I will provide:

- Implement Firebase Sign In and Sign Up
- Use Navigation Components and Fragments 
- Implement Dependency Injection using Dagger-Hilt
- Use of Clean Architecture ( Separation of Data, Domain and Presentation Layer)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Many contributors have already raised this issue, so please check other related issues before creating a duplicate.
