### ISSUE TITLE
Improvements in font size and style

### ISSUE THREAD

**Issue by Krishnaraj-shankar** [Taaveez/Taaveez-android#71]
### Is your feature request related to a problem? Please describe.

As a UI/UX Developer, I found this Mobile application contains Font-size and Font-style that are inappropriate for Mobile Apps. For any app, I truly believe fonts play a crucial role. It is a good first issue, assign this to a beginner @Suryansh1720001 

### Describe the solution you'd like

Trying various font styles and font size that suits the User Interface

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NANDHINI45** [comment]
sir I am interested to work on this issue kindly assign me this issue, I will change the font size and style for your project @Suryansh1720001

**Comment by Sachit-10** [comment]
@Vaibhav2002  I would like to work on this issue . I will change the font size and style according to the app.

**Comment by Suryansh1720001** [comment]
@Krishnaraj-shankar 
I believe the default font is suitable for this application. We cannot consider this an issue.
Thanks for understanding.
