### ISSUE TITLE
About adjusting the "setting" text 

### ISSUE THREAD

**Issue by shimmer12** [Taaveez/Taaveez-android#74]
### Is your feature request related to a problem? Please describe.

there is a problem of improper positioning of "setting " text 
![WhatsApp Image 2023-06-11 at 14 59 28](https://github.com/Taaveez/Taaveez-android/assets/92056170/0ada0010-cdb9-4f92-8d85-0496dc99ba96)

### Describe the solution you'd like

i would like to change the positioning of the text 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
@shimmer12
Actually, we cannot consider this as an issue. GSSOC does not allow changes in just a few words. Please select another issue for consideration.
Thanks for understanding.
