### ISSUE TITLE
Remake this app

### ISSUE THREAD

**Issue by sahilihas** [Taaveez/Taaveez-android#76]
### Is your feature request related to a problem? Please describe.

Hello!! I want to remake this application with new UI design and font styles using room architecture. Also want to add some vintage and old-school styles.
Please assign me this task in GSSOC'23. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hello @sahilihas 
You may consider issue number #47  for UI improvement. However, kindly ensure to thoroughly review all existing issues before creating a duplicate one.

**Comment by sahilihas** [comment]
okk sir
