### ISSUE TITLE
Attach images to notes

### ISSUE THREAD

**Issue by ManogjnaSinguluri** [Taaveez/Taaveez-android#99]
### Is your feature request related to a problem? Please describe.

I intend to add image feature where users can attach image while writing their notes so that they can effectively express their artwork 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManogjnaSinguluri** [comment]
@Vaibhav2002 @Suryansh1720001 I want to work on this feature as a part of Gssoc2023. Could you assign this issue to me

**Comment by Vaibhav2002** [comment]
@ManogjnaSinguluri i have a better idea, can you try adding markdown support in the editor, so users can write in markdown format, user can add images, add headings and all markdown formatting. The content is also display with the markdown formatting.
Can you do this?

**Comment by ManogjnaSinguluri** [comment]
Great! Sure I will do that

**Comment by Vaibhav2002** [comment]
> Great! Sure I will do that

Closing this issue
